resolver: nightly-2021-05-15

packages:
- .
- hspec-core
- hspec-discover
- hspec-discover/example
- hspec-discover/integration-test
- hspec-contrib

extra-deps:
- call-stack-0.4.0
- github: hspec/hspec
  commit: a9ac4cdcb928553d6ff734fd23109618e5f3d480
  subdirs:
    - hspec-meta
