name: build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: 0 0 * * *

jobs:
  build:
    name: ${{ matrix.os }} / Cabal ${{ matrix.cabal }} / GHC ${{ matrix.ghc }}
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os:
          - ubuntu-16.04 # https://launchpad.net/~hvr/+archive/ubuntu/ghc?field.series_filter=xenial
        cabal:
          - 3.4
        ghc:
          - 9.0.1
        include:
          - os: windows-latest
            ghc: latest
    steps:
      - uses: actions/checkout@v2
      - uses: haskell/actions/setup@08fca952ff0302e4ff725a413e48733e4c9b4127
        with:
          cabal-version: ${{ matrix.cabal }}
          ghc-version: ${{ matrix.ghc }}

      - uses: sol/run-haskell-tests@v1

      - name: Run regression tests
        run: |
          cabal install --lib --package-env test/regression/issue-169/
          test/regression/issue-169/run.sh
          cabal install --lib --package-env test/regression/issue-270/
          test/regression/issue-270/run.sh
        if: startsWith(matrix.ghc, '8.') && matrix.ghc != '8.0.1'

  success:
    needs: build
    runs-on: ubuntu-latest
    if: always() # this is required as GitHub considers "skipped" jobs as "passed" when checking branch protection rules

    steps:
      - run: exit 1
        if: needs.build.result != 'success'
